server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reknow
    username: postgres
    password: 194194
  jpa:
    hibernate:
      # data definition language Tự động tạo/cập nhật table
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Báo Hibernate dùng cú pháp SQL của PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: kieuhuydon@gmail.com
    password: mftg pgbr gqpo iihf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret-key: WfUn89mL5M3N5XjAUpWeHtaGJ7qLMXUq6FPiR1234567
  expiration: 86400000 # 1 ngày

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html